[sakura]
colorset1_fore=rgb(205,214,244)
colorset1_back=rgba(17,17,27,230)
colorset1_cursor=rgb(137,180,250)
font=Noto Sans Mono 11
show_always_first_tab=No
scrollbar=false
closebutton=true
tabs_on_bottom=false
less_questions=true
audible_bell=No
visible_bell=No
blinking_cursor=true
stop_tab_cycling_at_end_tabs=false
allow_bold=true
cursor_type=0
word_chars=-A-Za-z0-9,./?%&#:_=+@~
palette=custom
add_tab_accelerator=5
del_tab_accelerator=5
switch_tab_accelerator=8
move_tab_accelerator=6
copy_accelerator=1
scrollbar_accelerator=5
open_url_accelerator=5
font_size_accelerator=1
set_tab_name_accelerator=6
search_accelerator=5
select_all_accelerator=5
increase_font_size_accelerator=0
decrease_font_size_accelerator=0
full_screen_accelerator=0
show_tab_bar=multiple
urgent_bell=Yes
