# SleekOS Neofetch Configuration
print_info() {
    info title
    info underline
    info "OS" distro
    info "Host" model
    info "Kernel" kernel
    info "Uptime" uptime
    info "Packages" packages
    info "Shell" shell
    info "Resolution" resolution
    info "DE" de
    info "WM" wm
    info "Theme" theme
    info "Icons" icons
    info "Terminal" term
    info "CPU" cpu
    info "GPU" gpu
    info "Memory" memory
    info "Disk" disk
    info cols
}

title_fqdn="off"
kernel_shorthand="on"
distro_shorthand="off"
os_arch="on"
uptime_shorthand="tiny"
memory_percent="on"
package_managers="on"
shell_path="off"
shell_version="on"
speed_type="bios_limit"
speed_shorthand="off"
cpu_brand="on"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="off"
gpu_brand="on"
gpu_type="all"
refresh_rate="on"
gtk_shorthand="on"
gtk2="on"
gtk3="on"
de_version="off"
disk_show=('/')
colors=(4 6 4 4 4 7)
bold="on"
underline_enabled="on"
underline_char="─"
separator=" ➜"
color_blocks="on"
block_range=(0 15)
block_width=3
block_height=1
bar_char_elapsed="─"
bar_char_total="─"
bar_border="on"
bar_length=15
bar_color_elapsed="distro"
bar_color_total="distro"
image_backend="ascii"
image_source="auto"
ascii_distro="auto"
ascii_colors=(4 6 4 4 4 7)
ascii_bold="on"
