#!/usr/bin/env bash
set -euo pipefail

lb config noauto \
  --mode ubuntu \
  --architectures amd64 \
  --distribution noble \
  --archive-areas "main restricted universe multiverse" \
  --mirror-bootstrap "http://archive.ubuntu.com/ubuntu/" \
  --mirror-chroot "http://archive.ubuntu.com/ubuntu/" \
  --mirror-chroot-security "http://security.ubuntu.com/ubuntu/" \
  --binary-images iso-hybrid \
  --bootloader grub \
  --debian-installer false \
  --linux-flavours generic \
  --apt-recommends true \
  --bootappend-live "boot=live components splash username=operator hostname=winlikeos quiet" \
  "${@}"
